name: train_model
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - pip=21.2.4
  - python=3.8.10
  - mlflow=1.20.2
  - pytorch=1.6.0
  - torchvision=0.10.1
  - pip:
      - wandb==0.12.4
